# Generated by Django 5.2 on 2026-04-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='student_usn',
            field=models.CharField(default='1JB23CS001', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
