# Generated by Django 5.2 on 2026-04-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_student_usn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='student_usn',
        ),
        migrations.RemoveField(
            model_name='project',
            name='team_members',
        ),
        migrations.AddField(
            model_name='project',
            name='student1_name',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='student1_usn',
            field=models.CharField(default='NA', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='student2_name',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='student2_usn',
            field=models.CharField(default='NA', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='student3_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='student3_usn',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='student4_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='student4_usn',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
