# Generated by Django 6.0.1 on 2026-04-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_evaluation_certificate_copy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
