# Generated by Django 6.0.1 on 2026-04-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_guide_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='student1_email',
            field=models.EmailField(blank=True, help_text='Email for notification', max_length=254, null=True),
        ),
    ]
