databases:
  - name: pt-db
    databaseName: project_tracker
    user: tracker_user
    plan: free

services:
  - type: web
    name: student-project-tracker
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn student_project_tracker.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pt-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: RENDER
        value: "true"
